<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>fsm_state_machine</name>
  <version>0.1.0</version>
  <description>FSM 5 state (SEARCH/FOLLOW/APPROACH/LAND/COMPLETE) cho mission H-Pad landing</description>
  <maintainer email="mier@example.com">Mier</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>vdt_msgs</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>launch_testing_ament_cmake</test_depend>
  <test_depend>launch_ros</test_depend>
  <test_depend>ros2bag</test_depend>
  <test_depend>rosbag2_py</test_depend>
  <test_depend>rosbag2_storage_default_plugins</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>